### ISSUE TITLE
Error not able to visualize results

### ISSUE THREAD

**Issue by MritulaC** [llSourcell/3D_Pose_Estimation#3]
Hi,
 I am getting the following error when I try to run the demo and visualize:
Instructions for updating:
Use tf.cast instead.
train_dir experiments\All\dropout_0.5\epochs_1\lr_0.001\residual\depth_2\linear_size1024\batch_size_64\no_procrustes\maxnorm\batch_normalization\use_stacked_hourglass\predict_17
Could not find checkpoint. Aborting.
Traceback (most recent call last):
  File "src/predict_3dpose.py", line 537, in <module>
    tf.app.run()
  File "C:\Users\k1749021\AppData\Local\Continuum\anaconda3\envs\Lift_Deep1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/predict_3dpose.py", line 532, in main
    sample()
  File "src/predict_3dpose.py", line 424, in sample
    model = create_model(sess, actions, batch_size)
  File "src/predict_3dpose.py", line 137, in create_model
    raise( ValueError, "Checkpoint {0} does not seem to exist".format( ckpt.model_checkpoint_path ) )
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

The details requried are as below

1. Your operating system-Windows 10
2. Your tensorflow version-1,0
3. Your python version-3.7
4. The stack trace of the error that you see

**Comment by superSupa** [comment]
Did you find the solution?
I am facing this too
Please guide me
Thank you in advance!
