### ISSUE TITLE
`python src/predict_3dpose.py --camera_frame --residual --batch_norm --dropout 0.5 --max_norm --evaluateActionWise --use_sh --epochs 1`

### ISSUE THREAD

**Issue by garimss** [llSourcell/3D_Pose_Estimation#4]
got this error while running

W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: Failed to create a NewWriteableFile: experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\linear_size1024\batch_size_64\no_procrustes\maxnorm\batch_normalization\not_stacked_hourglass\predict_17\checkpoint-24371.data-00000-of-00001.tempstate14109936691770814557 : The system cannot find the path specified.
; No such process
Saving the model... Traceback (most recent call last):
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\linear_size1024\batch_size_64\no_procrustes\maxnorm\batch_normalization\not_stacked_hourglass\predict_17\checkpoint-24371.data-00000-of-00001.tempstate14109936691770814557 : The system cannot find the path specified.
; No such process
         [[{{node save/SaveV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/predict_3dpose.py", line 537, in <module>
    tf.app.run()
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/predict_3dpose.py", line 534, in main
    train()
  File "src/predict_3dpose.py", line 281, in train
    model.saver.save(sess, os.path.join(train_dir, 'checkpoint'), global_step=current_step )
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\training\saver.py", line 1188, in save
    raise exc
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\training\saver.py", line 1171, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\linear_size1024\batch_size_64\no_procrustes\maxnorm\batch_normalization\not_stacked_hourglass\predict_17\checkpoint-24371.data-00000-of-00001.tempstate14109936691770814557 : The system cannot find the path specified.
; No such process
         [[node save/SaveV2 (defined at D:\git_hub\3d-pose-baseline\src\linear_model.py:151) ]]

Caused by op 'save/SaveV2', defined at:
  File "src/predict_3dpose.py", line 537, in <module>
    tf.app.run()
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/predict_3dpose.py", line 534, in main
    train()
  File "src/predict_3dpose.py", line 171, in train
    model = create_model( sess, actions, FLAGS.batch_size )
  File "src/predict_3dpose.py", line 110, in create_model
    dtype=tf.float16 if FLAGS.use_fp16 else tf.float32)
  File "D:\git_hub\3d-pose-baseline\src\linear_model.py", line 151, in __init__
    self.saver = tf.train.Saver( tf.global_variables(), max_to_keep=10 )
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\training\saver.py", line 832, in __init__
    self.build()
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\training\saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\training\saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\training\saver.py", line 510, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\training\saver.py", line 210, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\training\saver.py", line 124, in save_op
    tensors)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1807, in save_v2
    name=name)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Failed to create a NewWriteableFile: experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\linear_size1024\batch_size_64\no_procrustes\maxnorm\batch_normalization\not_stacked_hourglass\predict_17\checkpoint-24371.data-00000-of-00001.tempstate14109936691770814557 : The system cannot find the path specified.
; No such process
         [[node save/SaveV2 (defined at D:\git_hub\3d-pose-baseline\src\linear_model.py:151) ]]

Thanks for your interest in our research!

If you have problems running our code, please include

1. Your operating system  **windows 10**
2. Your tensorflow version **1.13.1**
3. Your python version **3.7.2**
4. The stack trace of the error that you see

This is **research code**, and its primary purpose is to reproduce the scientific results that you see in our paper.
If you are looking for ways to extend our work such as 

* handling arbitrary images
* handling videos as input
* using other 2d detectors
* large-scale deployment
* handling missing data
* you want to make a startup out of this code

then pull requests are welcome, but it is very unlikely we will have the time to help you.

**Comment by garimss** [comment]
2019-06-20 14:45:37.336374: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: Failed to create a NewWriteableFile: experiments\All\dropout_0.5\epochs_1\lr_0.001\residual\depth_2\linear_size1024\batch_size_64\no_procrustes\maxnorm\batch_normalization\use_stacked_hourglass\predict_17\checkpoint-24371.data-00000-of-00001.tempstate14717617783826394263 : The system cannot find the path specified.
; No such process
Saving the model... Traceback (most recent call last):
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: experiments\All\dropout_0.5\epochs_1\lr_0.001\residual\depth_2\linear_size1024\batch_size_64\no_procrustes\maxnorm\batch_normalization\use_stacked_hourglass\predict_17\checkpoint-24371.data-00000-of-00001.tempstate14717617783826394263 : The system cannot find the path specified.
; No such process
         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, beta1_power/_107, beta2_power/_109, global_step, learning_rate/_111, linear_model/b1/_113, linear_model/b1/Adam/_115, linear_model/b1/Adam_1/_117, linear_model/b4/_119, linear_model/b4/Adam/_121, linear_model/b4/Adam_1/_123, linear_model/batch_normalization/beta/_125, linear_model/batch_normalization/beta/Adam/_127, linear_model/batch_normalization/beta/Adam_1/_129, linear_model/batch_normalization/gamma/_131, linear_model/batch_normalization/gamma/Adam/_133, linear_model/batch_normalization/gamma/Adam_1/_135, linear_model/batch_normalization/moving_mean/_137, linear_model/batch_normalization/moving_variance/_139, linear_model/two_linear_0/b2_0/_141, linear_model/two_linear_0/b2_0/Adam/_143, linear_model/two_linear_0/b2_0/Adam_1/_145, linear_model/two_linear_0/b3_0/_147, linear_model/two_linear_0/b3_0/Adam/_149, linear_model/two_linear_0/b3_0/Adam_1/_151, linear_model/two_linear_0/batch_normalization10/beta/_153, linear_model/two_linear_0/batch_normalization10/beta/Adam/_155, linear_model/two_linear_0/batch_normalization10/beta/Adam_1/_157, linear_model/two_linear_0/batch_normalization10/gamma/_159, linear_model/two_linear_0/batch_normalization10/gamma/Adam/_161, linear_model/two_linear_0/batch_normalization10/gamma/Adam_1/_163, linear_model/two_linear_0/batch_normalization10/moving_mean/_165, linear_model/two_linear_0/batch_normalization10/moving_variance/_167, linear_model/two_linear_0/batch_normalization20/beta/_169, linear_model/two_linear_0/batch_normalization20/beta/Adam/_171, linear_model/two_linear_0/batch_normalization20/beta/Adam_1/_173, linear_model/two_linear_0/batch_normalization20/gamma/_175, linear_model/two_linear_0/batch_normalization20/gamma/Adam/_177, linear_model/two_linear_0/batch_normalization20/gamma/Adam_1/_179, linear_model/two_linear_0/batch_normalization20/moving_mean/_181, linear_model/two_linear_0/batch_normalization20/moving_variance/_183, linear_model/two_linear_0/w2_0/_185, linear_model/two_linear_0/w2_0/Adam/_187, linear_model/two_linear_0/w2_0/Adam_1/_189, linear_model/two_linear_0/w3_0/_191, linear_model/two_linear_0/w3_0/Adam/_193, linear_model/two_linear_0/w3_0/Adam_1/_195, linear_model/two_linear_1/b2_1/_197, linear_model/two_linear_1/b2_1/Adam/_199, linear_model/two_linear_1/b2_1/Adam_1/_201, linear_model/two_linear_1/b3_1/_203, linear_model/two_linear_1/b3_1/Adam/_205, linear_model/two_linear_1/b3_1/Adam_1/_207, linear_model/two_linear_1/batch_normalization11/beta/_209, linear_model/two_linear_1/batch_normalization11/beta/Adam/_211, linear_model/two_linear_1/batch_normalization11/beta/Adam_1/_213, linear_model/two_linear_1/batch_normalization11/gamma/_215, linear_model/two_linear_1/batch_normalization11/gamma/Adam/_217, linear_model/two_linear_1/batch_normalization11/gamma/Adam_1/_219, linear_model/two_linear_1/batch_normalization11/moving_mean/_221, linear_model/two_linear_1/batch_normalization11/moving_variance/_223, linear_model/two_linear_1/batch_normalization21/beta/_225, linear_model/two_linear_1/batch_normalization21/beta/Adam/_227, linear_model/two_linear_1/batch_normalization21/beta/Adam_1/_229, linear_model/two_linear_1/batch_normalization21/gamma/_231, linear_model/two_linear_1/batch_normalization21/gamma/Adam/_233, linear_model/two_linear_1/batch_normalization21/gamma/Adam_1/_235, linear_model/two_linear_1/batch_normalization21/moving_mean/_237, linear_model/two_linear_1/batch_normalization21/moving_variance/_239, linear_model/two_linear_1/w2_1/_241, linear_model/two_linear_1/w2_1/Adam/_243, linear_model/two_linear_1/w2_1/Adam_1/_245, linear_model/two_linear_1/w3_1/_247, linear_model/two_linear_1/w3_1/Adam/_249, linear_model/two_linear_1/w3_1/Adam_1/_251, linear_model/w1/_253, linear_model/w1/Adam/_255, linear_model/w1/Adam_1/_257, linear_model/w4/_259, linear_model/w4/Adam/_261, linear_model/w4/Adam_1/_263)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/predict_3dpose.py", line 537, in <module>
    tf.app.run()
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/predict_3dpose.py", line 534, in main
    train()
  File "src/predict_3dpose.py", line 281, in train
    model.saver.save(sess, os.path.join(train_dir, 'checkpoint'), global_step=current_step )
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\saver.py", line 1637, in save
    raise exc
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\saver.py", line 1620, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: experiments\All\dropout_0.5\epochs_1\lr_0.001\residual\depth_2\linear_size1024\batch_size_64\no_procrustes\maxnorm\batch_normalization\use_stacked_hourglass\predict_17\checkpoint-24371.data-00000-of-00001.tempstate14717617783826394263 : The system cannot find the path specified.
; No such process
         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, beta1_power/_107, beta2_power/_109, global_step, learning_rate/_111, linear_model/b1/_113, linear_model/b1/Adam/_115, linear_model/b1/Adam_1/_117, linear_model/b4/_119, linear_model/b4/Adam/_121, linear_model/b4/Adam_1/_123, linear_model/batch_normalization/beta/_125, linear_model/batch_normalization/beta/Adam/_127, linear_model/batch_normalization/beta/Adam_1/_129, linear_model/batch_normalization/gamma/_131, linear_model/batch_normalization/gamma/Adam/_133, linear_model/batch_normalization/gamma/Adam_1/_135, linear_model/batch_normalization/moving_mean/_137, linear_model/batch_normalization/moving_variance/_139, linear_model/two_linear_0/b2_0/_141, linear_model/two_linear_0/b2_0/Adam/_143, linear_model/two_linear_0/b2_0/Adam_1/_145, linear_model/two_linear_0/b3_0/_147, linear_model/two_linear_0/b3_0/Adam/_149, linear_model/two_linear_0/b3_0/Adam_1/_151, linear_model/two_linear_0/batch_normalization10/beta/_153, linear_model/two_linear_0/batch_normalization10/beta/Adam/_155, linear_model/two_linear_0/batch_normalization10/beta/Adam_1/_157, linear_model/two_linear_0/batch_normalization10/gamma/_159, linear_model/two_linear_0/batch_normalization10/gamma/Adam/_161, linear_model/two_linear_0/batch_normalization10/gamma/Adam_1/_163, linear_model/two_linear_0/batch_normalization10/moving_mean/_165, linear_model/two_linear_0/batch_normalization10/moving_variance/_167, linear_model/two_linear_0/batch_normalization20/beta/_169, linear_model/two_linear_0/batch_normalization20/beta/Adam/_171, linear_model/two_linear_0/batch_normalization20/beta/Adam_1/_173, linear_model/two_linear_0/batch_normalization20/gamma/_175, linear_model/two_linear_0/batch_normalization20/gamma/Adam/_177, linear_model/two_linear_0/batch_normalization20/gamma/Adam_1/_179, linear_model/two_linear_0/batch_normalization20/moving_mean/_181, linear_model/two_linear_0/batch_normalization20/moving_variance/_183, linear_model/two_linear_0/w2_0/_185, linear_model/two_linear_0/w2_0/Adam/_187, linear_model/two_linear_0/w2_0/Adam_1/_189, linear_model/two_linear_0/w3_0/_191, linear_model/two_linear_0/w3_0/Adam/_193, linear_model/two_linear_0/w3_0/Adam_1/_195, linear_model/two_linear_1/b2_1/_197, linear_model/two_linear_1/b2_1/Adam/_199, linear_model/two_linear_1/b2_1/Adam_1/_201, linear_model/two_linear_1/b3_1/_203, linear_model/two_linear_1/b3_1/Adam/_205, linear_model/two_linear_1/b3_1/Adam_1/_207, linear_model/two_linear_1/batch_normalization11/beta/_209, linear_model/two_linear_1/batch_normalization11/beta/Adam/_211, linear_model/two_linear_1/batch_normalization11/beta/Adam_1/_213, linear_model/two_linear_1/batch_normalization11/gamma/_215, linear_model/two_linear_1/batch_normalization11/gamma/Adam/_217, linear_model/two_linear_1/batch_normalization11/gamma/Adam_1/_219, linear_model/two_linear_1/batch_normalization11/moving_mean/_221, linear_model/two_linear_1/batch_normalization11/moving_variance/_223, linear_model/two_linear_1/batch_normalization21/beta/_225, linear_model/two_linear_1/batch_normalization21/beta/Adam/_227, linear_model/two_linear_1/batch_normalization21/beta/Adam_1/_229, linear_model/two_linear_1/batch_normalization21/gamma/_231, linear_model/two_linear_1/batch_normalization21/gamma/Adam/_233, linear_model/two_linear_1/batch_normalization21/gamma/Adam_1/_235, linear_model/two_linear_1/batch_normalization21/moving_mean/_237, linear_model/two_linear_1/batch_normalization21/moving_variance/_239, linear_model/two_linear_1/w2_1/_241, linear_model/two_linear_1/w2_1/Adam/_243, linear_model/two_linear_1/w2_1/Adam_1/_245, linear_model/two_linear_1/w3_1/_247, linear_model/two_linear_1/w3_1/Adam/_249, linear_model/two_linear_1/w3_1/Adam_1/_251, linear_model/w1/_253, linear_model/w1/Adam/_255, linear_model/w1/Adam_1/_257, linear_model/w4/_259, linear_model/w4/Adam/_261, linear_model/w4/Adam_1/_263)]]

Caused by op 'save/SaveV2', defined at:
  File "src/predict_3dpose.py", line 537, in <module>
    tf.app.run()
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/predict_3dpose.py", line 534, in main
    train()
  File "src/predict_3dpose.py", line 171, in train
    model = create_model( sess, actions, FLAGS.batch_size )
  File "src/predict_3dpose.py", line 110, in create_model
    dtype=tf.float16 if FLAGS.use_fp16 else tf.float32)
  File "D:\git_hub\3d-pose-baseline\src\linear_model.py", line 151, in __init__
    self.saver = tf.train.Saver( tf.global_variables(), max_to_keep=10 )
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\saver.py", line 1281, in __init__
    self.build()
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\saver.py", line 775, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\saver.py", line 275, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\saver.py", line 193, in save_op
    tensors)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1800, in save_v2
    shape_and_slices=shape_and_slices, tensors=tensors, name=name)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "C:\Users\Garima\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Failed to create a NewWriteableFile: experiments\All\dropout_0.5\epochs_1\lr_0.001\residual\depth_2\linear_size1024\batch_size_64\no_procrustes\maxnorm\batch_normalization\use_stacked_hourglass\predict_17\checkpoint-24371.data-00000-of-00001.tempstate14717617783826394263 : The system cannot find the path specified.
; No such process
         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, beta1_power/_107, beta2_power/_109, global_step, learning_rate/_111, linear_model/b1/_113, linear_model/b1/Adam/_115, linear_model/b1/Adam_1/_117, linear_model/b4/_119, linear_model/b4/Adam/_121, linear_model/b4/Adam_1/_123, linear_model/batch_normalization/beta/_125, linear_model/batch_normalization/beta/Adam/_127, linear_model/batch_normalization/beta/Adam_1/_129, linear_model/batch_normalization/gamma/_131, linear_model/batch_normalization/gamma/Adam/_133, linear_model/batch_normalization/gamma/Adam_1/_135, linear_model/batch_normalization/moving_mean/_137, linear_model/batch_normalization/moving_variance/_139, linear_model/two_linear_0/b2_0/_141, linear_model/two_linear_0/b2_0/Adam/_143, linear_model/two_linear_0/b2_0/Adam_1/_145, linear_model/two_linear_0/b3_0/_147, linear_model/two_linear_0/b3_0/Adam/_149, linear_model/two_linear_0/b3_0/Adam_1/_151, linear_model/two_linear_0/batch_normalization10/beta/_153, linear_model/two_linear_0/batch_normalization10/beta/Adam/_155, linear_model/two_linear_0/batch_normalization10/beta/Adam_1/_157, linear_model/two_linear_0/batch_normalization10/gamma/_159, linear_model/two_linear_0/batch_normalization10/gamma/Adam/_161, linear_model/two_linear_0/batch_normalization10/gamma/Adam_1/_163, linear_model/two_linear_0/batch_normalization10/moving_mean/_165, linear_model/two_linear_0/batch_normalization10/moving_variance/_167, linear_model/two_linear_0/batch_normalization20/beta/_169, linear_model/two_linear_0/batch_normalization20/beta/Adam/_171, linear_model/two_linear_0/batch_normalization20/beta/Adam_1/_173, linear_model/two_linear_0/batch_normalization20/gamma/_175, linear_model/two_linear_0/batch_normalization20/gamma/Adam/_177, linear_model/two_linear_0/batch_normalization20/gamma/Adam_1/_179, linear_model/two_linear_0/batch_normalization20/moving_mean/_181, linear_model/two_linear_0/batch_normalization20/moving_variance/_183, linear_model/two_linear_0/w2_0/_185, linear_model/two_linear_0/w2_0/Adam/_187, linear_model/two_linear_0/w2_0/Adam_1/_189, linear_model/two_linear_0/w3_0/_191, linear_model/two_linear_0/w3_0/Adam/_193, linear_model/two_linear_0/w3_0/Adam_1/_195, linear_model/two_linear_1/b2_1/_197, linear_model/two_linear_1/b2_1/Adam/_199, linear_model/two_linear_1/b2_1/Adam_1/_201, linear_model/two_linear_1/b3_1/_203, linear_model/two_linear_1/b3_1/Adam/_205, linear_model/two_linear_1/b3_1/Adam_1/_207, linear_model/two_linear_1/batch_normalization11/beta/_209, linear_model/two_linear_1/batch_normalization11/beta/Adam/_211, linear_model/two_linear_1/batch_normalization11/beta/Adam_1/_213, linear_model/two_linear_1/batch_normalization11/gamma/_215, linear_model/two_linear_1/batch_normalization11/gamma/Adam/_217, linear_model/two_linear_1/batch_normalization11/gamma/Adam_1/_219, linear_model/two_linear_1/batch_normalization11/moving_mean/_221, linear_model/two_linear_1/batch_normalization11/moving_variance/_223, linear_model/two_linear_1/batch_normalization21/beta/_225, linear_model/two_linear_1/batch_normalization21/beta/Adam/_227, linear_model/two_linear_1/batch_normalization21/beta/Adam_1/_229, linear_model/two_linear_1/batch_normalization21/gamma/_231, linear_model/two_linear_1/batch_normalization21/gamma/Adam/_233, linear_model/two_linear_1/batch_normalization21/gamma/Adam_1/_235, linear_model/two_linear_1/batch_normalization21/moving_mean/_237, linear_model/two_linear_1/batch_normalization21/moving_variance/_239, linear_model/two_linear_1/w2_1/_241, linear_model/two_linear_1/w2_1/Adam/_243, linear_model/two_linear_1/w2_1/Adam_1/_245, linear_model/two_linear_1/w3_1/_247, linear_model/two_linear_1/w3_1/Adam/_249, linear_model/two_linear_1/w3_1/Adam_1/_251, linear_model/w1/_253, linear_model/w1/Adam/_255, linear_model/w1/Adam_1/_257, linear_model/w4/_259, linear_model/w4/Adam/_261, linear_model/w4/Adam_1/_263)]]
